server:
  #端口号
  port: 8089
  tomcat:
    uri-encoding: UTF-8

#mybatis
mybatis:
  mapper-locations: classpath*:mapping/**/*.xml,classpath*:com/zx/**/dao/*.xml
  config-location: classpath:config/mybatis-config.xml

#datasource
spring:
  datasource:
    #账号密码
    username: root
    password: 123456
    url: jdbc:mysql://49.232.139.221:3306/curriculum_assessment?useUnicode=true&characterEncoding=utf-8
    # 使用druid数据源连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #驱动
    driver-class-name: com.mysql.jdbc.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true

  #redis
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 172.26.1.180
    #    host: 172.26.1.152
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    #password: root
    # 连接超时时间（毫秒）
    timeout: 3600
    # springboot 中redis默认使用lettuce, 本系统使用jedis, 如果要用默认的,配置上只需要将jedis换成lettuce即可
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

#logback日志配置
logging:
  config: classpath:config/logback-spring.xml
  #日志存放目录
  path: D:/logs

#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  #用pagehelper的count
  default-count: true

#JWT
jwt:
  #有效时间(s)
  expiresecond: 3600




